# Name: ALXEN07ds

Replace the above Name with your attendance code


### Action_1:

Rename this Azure Jupyper notebook to include your attendance code. Week11_ds2019_(YOUR_ATTENDANCE_CODE)

* example : Week11_ds2019_--##ds

# Machine Learning Algorithm



### Instructions

* For each of the following questions below, write corresponding Python code that answers each question.
* Remember to set your Python Interpreter to Python 3.6 and above.
* Discretionary points will be awarded for attempts made to answer each question.
* Each student is encouraged to work independently in arriving at the solutions.


#### 1. Importing packages 

You will need the following packages/libraries for this assignment:

a) Data loading and manipulating: Pandas and Numpy

b) Machine Learning models: sklearn

Hint: import assessment as ds
         from ds import assessment

In [22]:
# import packages
import pandas as pd
import numpy as np
import sklearn as skl
import sklearn.metrics as sklm
from sklearn.model_selection import train_test_split

from sklearn import linear_model

#### 2. Loading the data

After downloading the data from http://tiny.cc/19hqfz, load the train and test data


Hint: package.read_csv(train.csv)

In [23]:
# read data
train_df = pd.read_csv("train_.csv")
test_df = pd.read_csv('test_.csv')

#sample the dataframes
print(train_df.sample(5))
print(test_df.sample(5))

     Gender Married Dependents Education Self_Employed  ApplicantIncome  \
76     Male      No          0  Graduate            No             3750   
312  Female      No          0  Graduate            No             2507   
502    Male     Yes          2  Graduate            No             4865   
554    Male     Yes          0  Graduate            No             3593   
306  Female      No          0  Graduate            No             3762   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
76              4750.0       176.0             360.0             1.0   
312                0.0        56.0             360.0             1.0   
502             5624.0       208.0             360.0             1.0   
554             4266.0       132.0             180.0             0.0   
306             1666.0       135.0             360.0             1.0   

    Property_Area  Loan_Status  
76          Urban            0  
312         Rural            1  
502     Semiurban

#### 3. Data cleaning and exploration

After loading the data, explore and clean the data in preparation for training. 

Hint: 
a) List of column

b) View the data rows (can view the first few rows or columns)

c) Types of data columns

d) Summary statistics of the data


Note: You can tackle each section in code block

In [24]:
# list columns of the train dataframe
train_df.columns


Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [25]:
# View row sample of train dataframe
train_df.sample(10)

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
19     Male     Yes          0      Graduate           NaN             2600   
83     Male     Yes          0      Graduate            No             6000   
361    Male     Yes          2      Graduate            No             5000   
581    Male      No          0      Graduate            No             1836   
333    Male     Yes          0      Graduate           NaN            63337   
159    Male     Yes          0      Graduate            No             4583   
564    Male     Yes          2      Graduate            No             8799   
220    Male     Yes          0      Graduate            No             2221   
346    Male     Yes        NaN  Not Graduate            No             3523   
233  Female      No          0      Graduate            No             8333   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
19              3500.0       115.0               NaN             1.0   
83              2250.0       265.0             360.0             NaN   
361             3667.0       236.0             360.0             1.0   
581            33837.0        90.0             360.0             1.0   
333                0.0       490.0             180.0             1.0   
159             5625.0       255.0             360.0             1.0   
564                0.0       258.0             360.0             0.0   
220                0.0        60.0             360.0             0.0   
346             3230.0       152.0             360.0             0.0   
233                0.0       280.0             360.0             1.0   

    Property_Area  Loan_Status  
19          Urban            1  
83      Semiurban            0  
361     Semiurban            1  
581         Urban            0  
333         Urban            1  
159     Semiurban            1  
564         Urban            0  
220         Urban            0  
346         Rural            0  
233     Semiurban            1

In [26]:
# Look at the column data type in the train dataframe
train_df.dtypes

Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status            int64
dtype: object

In [27]:
# Statistical analysis of the train dataframe
train_df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  Loan_Status  
count      564.000000   614.000000  
mean         0.842199     0.687296  
std          0.364878     0.463973  
min          0.000000     0.000000  
25%          1.000000     0.000000  
50%          1.000000     1.000000  
75%          1.000000     1.000000  
max          1.000000     1.000000

#### 4. Find missing values

Hint: 
Find the sum of the missing values

In [28]:
# Find the missing values in the train dataframe
train_df.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

#### 5. Handle the missing values 

Hint: 
There are a number of techniques to do so, use any that works for you.

In [29]:
# Count the unique values in the Credit_History column
train_df.Credit_History.value_counts()

1.0    475
0.0     89
Name: Credit_History, dtype: int64

In [30]:
#Replace all the missing by replacing with the min,mean or dropping the rows

#Replace with min
train_df.Credit_History.fillna(0.0, inplace = True)
train_df.Dependents.fillna(0, inplace = True)
#Replace with mean
train_df.LoanAmount.fillna(train_df.LoanAmount.mean(),inplace = True)
train_df.Loan_Amount_Term.fillna(train_df.Loan_Amount_Term.mean(),inplace= True)

#Let's see what we have
train_df.isnull().sum()

Gender               13
Married               3
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [31]:
#Drop empty rows
train_df.dropna(axis=0, inplace=True)

#Let's see what we have
train_df.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [32]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 566 entries, 0 to 613
Data columns (total 12 columns):
Gender               566 non-null object
Married              566 non-null object
Dependents           566 non-null object
Education            566 non-null object
Self_Employed        566 non-null object
ApplicantIncome      566 non-null int64
CoapplicantIncome    566 non-null float64
LoanAmount           566 non-null float64
Loan_Amount_Term     566 non-null float64
Credit_History       566 non-null float64
Property_Area        566 non-null object
Loan_Status          566 non-null int64
dtypes: float64(4), int64(2), object(6)
memory usage: 57.5+ KB


In [33]:
train_df.Property_Area.unique()
train_df.Property_Area[151]

'Rural'

#### 6. Other pre-processing techniques

Hint: 
Feature selection

In [34]:
# encode some columns with binary encoding
train_df = pd.get_dummies(train_df, columns = ['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area'])
# cols = {'Gender':{'Male':0, 'Female':1}, 
#         'Married':{'No':0, 'Yes':1}, 
#         'Dependents':{'0':0, '1':1, '2':2, '3+':3}, 
#         'Education':{'Graduate':1, 'Not Graduate':0}, 
#         'Self_Employed':{'No':0, 'Yes':1},
#         'Property_Area':{'Urban':0, 'Rural':1, 'Semiurban':2}
#        }
# for key in cols:
#     for k in cols[key]:
#         train_df = train_df.replace(to_replace=k, value=cols[key].get(k))
train_df.sample(3)

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
526             3775                0.0       110.0             360.0   
135             4000             7750.0       290.0             360.0   
125             3692                0.0        93.0             360.0   

     Credit_History  Loan_Status  Gender_Female  Gender_Male  Married_No  \
526             1.0            1              0            1           0   
135             1.0            0              0            1           0   
125             0.0            1              1            0           1   

     Married_Yes         ...           Dependents_1  Dependents_2  \
526            1         ...                      0             0   
135            1         ...                      0             0   
125            0         ...                      0             0   

     Dependents_3+  Education_Graduate  Education_Not Graduate  \
526              0                   1                       0   
135              1                   1                       0   
125              0                   1                       0   

     Self_Employed_No  Self_Employed_Yes  Property_Area_Rural  \
526                 1                  0                    0   
135                 1                  0                    0   
125                 1                  0                    1   

     Property_Area_Semiurban  Property_Area_Urban  
526                        1                    0  
135                        1                    0  
125                        0                    0  

[3 rows x 22 columns]

In [35]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 566 entries, 0 to 613
Data columns (total 22 columns):
ApplicantIncome            566 non-null int64
CoapplicantIncome          566 non-null float64
LoanAmount                 566 non-null float64
Loan_Amount_Term           566 non-null float64
Credit_History             566 non-null float64
Loan_Status                566 non-null int64
Gender_Female              566 non-null uint8
Gender_Male                566 non-null uint8
Married_No                 566 non-null uint8
Married_Yes                566 non-null uint8
Dependents_0               566 non-null uint8
Dependents_0               566 non-null uint8
Dependents_1               566 non-null uint8
Dependents_2               566 non-null uint8
Dependents_3+              566 non-null uint8
Education_Graduate         566 non-null uint8
Education_Not Graduate     566 non-null uint8
Self_Employed_No           566 non-null uint8
Self_Employed_Yes          566 non-null uint8
Property_Area

#### 8. Implement a predictive model

Hint: 
Logistic Regression

In [36]:
# Split data  and make loan status column the y label
y_label = train_df.Loan_Status
x_train, x_test, y_train, y_test = train_test_split(train_df.drop("Loan_Status", axis = 1), y_label, test_size=0.2, shuffle=True)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(452, 21) (114, 21) (452,) (114,)


In [37]:
# Train model
log_mod = linear_model.LogisticRegression() 
log_mod.fit(x_train, y_train)

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [38]:
# Predict the test label
prediction = log_mod.predict_proba(x_test)
prediction[:5,:]

array([[0.11529259, 0.88470741],
       [0.26717661, 0.73282339],
       [0.08438786, 0.91561214],
       [0.58367181, 0.41632819],
       [0.27795026, 0.72204974]])

#### 9. Evaluate your predictive model
Hint: 
How do you evaluate a classifier model

In [39]:
# Encode the probability of the prdiction as binary
results = np.array([1 if pred > 0.5 else 0 for pred in prediction[:,1]])
results

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1])

In [40]:
# Evaluate Model
metrics = sklm.precision_recall_fscore_support(y_test, results)
conf = sklm.confusion_matrix(y_test, results)
accuracy=sklm.accuracy_score(y_test, results)

In [41]:
metrics

(array([0.8       , 0.80898876]),
 array([0.54054054, 0.93506494]),
 array([0.64516129, 0.86746988]),
 array([37, 77], dtype=int64))

In [42]:
# Print out the metrics
print('                 Confusion matrix')
print('                     positive        negative')
print('Actual positive    %6d' % conf[0,0] + '             %5d' % conf[0,1])
print('Actual negative    %6d' % conf[1,0] + '             %5d' % conf[1,1])
print('')
print('Accuracy  %0.2f' % accuracy)
print(' ')
print('           Positive      Negative')
print('Num case   %6d' % metrics[3][0] + '        %6d' % metrics[3][1])
print('Precision  %6.2f' % metrics[0][0] + '        %6.2f' % metrics[0][1])
print('Recall     %6.2f' % metrics[1][0] + '        %6.2f' % metrics[1][1])
print('F1         %6.2f' % metrics[2][0] + '        %6.2f' % metrics[2][1])

                 Confusion matrix
                     positive        negative
Actual positive        20                17
Actual negative         5                72

Accuracy  0.81
 
           Positive      Negative
Num case       37            77
Precision    0.80          0.81
Recall       0.54          0.94
F1           0.65          0.87
